# Generated by Django 3.2.6 on 2022-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Заявка с сайта',
                'verbose_name_plural': 'Заявки с сайта',
            },
        ),
        migrations.CreateModel(
            name='FeedBackMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН должника')),
                ('name_debt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование должника')),
                ('sud', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=255, null=True, verbose_name='Получено судебное решение?')),
                ('sum_debt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма долга, руб')),
                ('list', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=255, null=True, verbose_name='Получен исполнительный лист?')),
            ],
            options={
                'verbose_name': 'Заявка на продажу долга',
                'verbose_name_plural': 'Заявки на продажу долгов',
            },
        ),
    ]
