# Generated by Django 4.0.4 on 2022-04-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmoney',
            old_name='sum',
            new_name='sum_debt',
        ),
    ]
