# Generated by Django 3.2.6 on 2022-04-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_feedbackmoney_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmoney',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedbackmoney',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН должника'),
        ),
        migrations.AlterField(
            model_name='feedbackmoney',
            name='list',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=255, null=True, verbose_name='Получен исполнительный лист?'),
        ),
        migrations.AlterField(
            model_name='feedbackmoney',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedbackmoney',
            name='name_debt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование должника'),
        ),
        migrations.AlterField(
            model_name='feedbackmoney',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedbackmoney',
            name='sud',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=255, null=True, verbose_name='Получено судебное решение?'),
        ),
        migrations.AlterField(
            model_name='feedbackmoney',
            name='sum_debt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма долга, руб'),
        ),
    ]
