# Generated by Django 3.2.6 on 2022-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectNumber', models.CharField(db_index=True, max_length=150, verbose_name='Наименование проекта')),
                ('statusProject', models.CharField(choices=[('active', 'Активный'), ('completed', 'Архивный')], max_length=250, verbose_name='Статус проекта')),
                ('category', models.CharField(choices=[('open', 'Открыт для инвестиций'), ('closed', 'Закрыт для инвестиций')], max_length=250, verbose_name='Категория долга:')),
                ('amountDebts', models.IntegerField(verbose_name='Номинал долга:')),
                ('amountRecovery', models.IntegerField(verbose_name='Плановая сумма взыскания:')),
                ('amountBye', models.IntegerField(verbose_name='Стоимость покупки:')),
                ('amountCosts', models.IntegerField(verbose_name='Проектные расходы:')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Дисконт, %')),
                ('planned_collection_period', models.IntegerField(blank=True, null=True, verbose_name='Плановый срок взыскания')),
                ('planned_financial_result', models.IntegerField(blank=True, null=True, verbose_name='Плановый финансовый результат')),
                ('manager_planned_remuneration', models.IntegerField(blank=True, null=True, verbose_name='Плановое вознаграждение управляющего')),
                ('investor_planned_financial_result', models.IntegerField(blank=True, null=True, verbose_name='Плановый финансовый результат инвестора')),
                ('planned_profitability_project', models.IntegerField(blank=True, null=True, verbose_name='Плановая доходность проекта, %')),
                ('planned_annual_return', models.IntegerField(blank=True, null=True, verbose_name='Плановая годовая доходность, %')),
                ('investor_planned_annual_return', models.IntegerField(blank=True, null=True, verbose_name='Плановая годовая доходность инвестора, %')),
                ('free_for_investment', models.IntegerField(blank=True, null=True, verbose_name='Свободно для инвестиций')),
                ('investments_are_accepted_until', models.DateField(blank=True, null=True, verbose_name='Инвестиции принимаются до')),
                ('actual_amount_recovery', models.IntegerField(blank=True, null=True, verbose_name='Фактическая сумма взыскания')),
                ('actual_costs', models.IntegerField(blank=True, null=True, verbose_name='Фактические расходы')),
                ('actual_term_collection', models.IntegerField(blank=True, null=True, verbose_name='Фактический срок взыскания')),
                ('actual_financial_result', models.IntegerField(blank=True, null=True, verbose_name='Фактический финансовый результат')),
                ('actual_remuneration_manager', models.IntegerField(blank=True, null=True, verbose_name='Фактическое вознаграждение управляющего')),
                ('actual_financial_result_investor', models.IntegerField(blank=True, null=True, verbose_name='Фактический финансовый результат инвестора')),
                ('actual_year_return', models.IntegerField(blank=True, null=True, verbose_name='Фактическая годовая доходность, %')),
                ('actual_investor_year_return', models.IntegerField(blank=True, null=True, verbose_name='Фактическая годовая доходность инвестора, %')),
                ('total_investment_amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма инвестиций всего')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-date_pub'],
            },
        ),
    ]
