# Generated by Django 4.0.4 on 2022-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investpost',
            name='planned_profitability_project',
            field=models.FloatField(blank=True, null=True, verbose_name='Плановая доходность проекта, %'),
        ),
    ]
