# Generated by Django 4.0.4 on 2022-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_investpost_planned_profitability_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investpost',
            name='investor_planned_annual_return',
            field=models.FloatField(blank=True, null=True, verbose_name='Плановая годовая доходность инвестора, %'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='planned_annual_return',
            field=models.FloatField(blank=True, null=True, verbose_name='Плановая годовая доходность, %'),
        ),
    ]
