# Generated by Django 4.0.4 on 2022-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_investpost_planned_collection_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investpost',
            name='actual_amount_recovery',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическая сумма взыскания'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='actual_remuneration_manager',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическое вознаграждение управляющего'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='actual_term_collection',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактический срок взыскания'),
        ),
    ]
