# Generated by Django 4.0.4 on 2022-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_investpost_actual_amount_recovery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investpost',
            name='actual_amount_recovery',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактическая сумма взыскания'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='actual_remuneration_manager',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактическое вознаграждение управляющего'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='actual_term_collection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактический срок взыскания'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='investor_planned_annual_return',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плановая годовая доходность инвестора, %'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='planned_annual_return',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плановая годовая доходность, %'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='planned_collection_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плановый срок взыскания'),
        ),
        migrations.AlterField(
            model_name='investpost',
            name='planned_profitability_project',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плановая доходность проекта, %'),
        ),
    ]
